import React from 'react';
import { ArrowRight, ChevronRight } from 'lucide-react';
import { ToolboxTalk } from '../types';
interface DashboardProps { talks: ToolboxTalk[]; onNewTalk: () => void; onEditTalk: (id: string) => void; }
const todayIso = () => new Date(Date.now() - new Date().getTimezoneOffset() * 60_000).toISOString().slice(0, 10);
export const Dashboard: React.FC<DashboardProps> = ({ talks, onNewTalk, onEditTalk }) => {
  const today = todayIso(); const todayFiled = talks.some((talk) => talk.date === today && talk.submittedAt); const draft = talks.find((talk) => !talk.submittedAt); const filed = talks.filter((talk) => talk.submittedAt).slice(0, 3); const quarterCount = talks.filter((talk) => talk.submittedAt && new Date(talk.date).getMonth() >= Math.floor(new Date().getMonth() / 3) * 3).length;
  return <main className="mx-auto max-w-[760px] px-5 pb-32 pt-8"><p className="snd-label text-accent">{today}</p><h1 className="mt-3 max-w-[22ch] text-[36px] font-bold leading-[1.08] tracking-[-.025em] text-ink">{todayFiled ? "Today's talk is filed." : 'Nothing logged yet today.'}</h1><p className="mt-4 max-w-[56ch] text-[17px] leading-[1.6] text-ink-body">One talk, one record, and you're covered for the day. Start with what the crew is actually doing.</p>
    <button onClick={onNewTalk} className="mt-8 flex min-h-[72px] w-full items-center justify-between rounded-[10px] bg-accent px-6 text-left text-white transition-colors hover:bg-accent-hover active:bg-accent-press"><span><span className="block text-xl font-bold">Start today's talk</span><span className="snd-mono mt-1 block text-xs">Talk it through · about 4 minutes</span></span><ArrowRight size={25} strokeWidth={1.75} /></button>
    {draft && <button onClick={() => onEditTalk(draft.id)} className="mt-3 flex min-h-16 w-full items-center justify-between border border-rule bg-sheet px-4 text-left hover:border-accent"><span><span className="snd-label inline-block border border-[#F3E2C7] bg-caution-tint px-2 py-1 text-caution-text">Unfinished</span><span className="ml-3 font-semibold text-ink">{draft.title || "Today's toolbox talk"}</span><span className="snd-mono mt-2 block text-xs text-ink-muted">Left off at {draft.draftStep === 2 ? 'the crew list' : draft.draftStep === 3 ? 'the send step' : 'the talk'} · saved on device</span></span><ChevronRight size={20} className="text-ink-muted" /></button>}
    <div className="mt-12 flex items-baseline justify-between"><h2 className="text-xl font-bold tracking-[-.02em] text-ink">Your last few records</h2><span className="snd-label text-accent">See all</span></div><div className="mt-4 border border-rule bg-sheet">{filed.length ? filed.map((talk, index) => { const present = talk.attendees.filter((attendee) => attendee.present).length; return <button key={talk.id} onClick={() => onEditTalk(talk.id)} className={`flex min-h-16 w-full items-center justify-between px-4 text-left hover:bg-ground ${index ? 'border-t border-rule-soft' : ''}`}><span><span className="block font-semibold text-ink">{talk.title || 'Toolbox talk record'}</span><span className="snd-mono mt-1 block text-xs text-ink-muted">{talk.date} · {talk.location || 'Location not set'} · {present}/{talk.attendees.length} present</span></span><span className="snd-label border border-[#BDE7C9] bg-ok-tint px-2 py-1 text-ok-text">Sent</span></button>; }) : <p className="px-4 py-8 text-[16px] text-ink-muted">Your filed talks will live here.</p>}</div><p className="snd-mono mt-4 text-xs text-ink-faint">{quarterCount} record{quarterCount === 1 ? '' : 's'} this quarter · all filed, none missing</p>
  </main>;
};
