import React from 'react';
import { Check, Plus } from 'lucide-react';
import { Recipient } from '../types';
import { auth } from '../utils/auth';
interface Props { recipients: Recipient[]; onUpdateRecipients: (recipients: Recipient[]) => void; }
export const RecipientsSelector: React.FC<Props> = ({ recipients, onUpdateRecipients }) => {
  const [showAdd, setShowAdd] = React.useState(false); const [name, setName] = React.useState(''); const [email, setEmail] = React.useState(''); const selected = recipients.filter((recipient) => recipient.selected).length;
  const [error, setError] = React.useState('');
  const add = () => { if (!name.trim() || !auth.isValidEmail(email.trim())) { setError('Enter a name and a valid email address.'); return; } if (recipients.some(recipient => recipient.email.toLowerCase() === email.trim().toLowerCase())) { setError('This email address is already on the list.'); return; } setError(''); onUpdateRecipients([...recipients, { id: `recipient_${Date.now()}`, name: name.trim(), email: email.trim(), selected: true }]); setName(''); setEmail(''); setShowAdd(false); };
  return <div className="border border-rule bg-sheet"><div className="flex items-center justify-between border-b border-rule-soft px-4 py-3"><span className="snd-label text-ink-muted">Goes to · {selected} selected</span><button onClick={() => setShowAdd((current) => !current)} className="min-h-11 border border-rule px-3 text-sm font-semibold text-ink hover:border-accent"><Plus className="mr-1 inline" size={17} />Someone else</button></div>
    {error && <p role="alert" className="px-3 pt-3 text-sm text-stop-text">{error}</p>}
    {showAdd && <div className="grid gap-2 border-b border-rule-soft p-3 sm:grid-cols-[1fr_1fr_auto]"><input aria-label="Recipient name" value={name} onChange={(event) => setName(event.target.value)} className="min-h-[52px] min-w-0 border border-rule px-3 text-[16px]" placeholder="Name" /><input type="email" aria-label="Recipient email" value={email} onChange={(event) => setEmail(event.target.value)} className="min-h-[52px] min-w-0 border border-rule px-3 text-[16px]" placeholder="email@company.com" /><button onClick={add} className="min-h-[52px] bg-accent px-4 font-bold text-white hover:bg-accent-hover">Add</button></div>}
    {recipients.length ? recipients.map((recipient, index) => <button key={recipient.id} onClick={() => onUpdateRecipients(recipients.map((item) => item.id === recipient.id ? { ...item, selected: !item.selected } : item))} className={`flex min-h-16 w-full items-center gap-3 px-4 text-left ${index ? 'border-t border-rule-soft' : ''}`}><span className={`grid h-7 w-7 shrink-0 place-items-center rounded-[6px] border-2 ${recipient.selected ? 'border-ok bg-ok text-white' : 'border-[#CFC8BE] bg-sheet'}`}>{recipient.selected && <Check size={18} strokeWidth={3} />}</span><span className="min-w-0 break-words"><span className="block font-semibold text-[16px] text-ink">{recipient.name}</span><span className="snd-mono mt-1 block text-xs text-ink-muted">{recipient.email}</span></span><span className="snd-mono ml-auto shrink-0 text-xs text-ink-faint">Email</span></button>) : <p className="px-4 py-8 text-sm text-ink-muted">Add the people who need a copy of this record.</p>}
  </div>;
};
